spring:
  application:
    name: central-config-server
  profiles:
    #active: native
    active: git
    cloud:
      config:
        server:
            git:
                uri:
          #native:
            #searchLocations: "classapth:/config"

server:
    port: 8071
